sudo: required
language: node_js
env:
  - PORT=6030 REDIS_PORT=6379 REDIS_HOST='redis' NODE_ENV='test' LOG_LEVEL=info

node_js:
  - 14
services:
  - docker
# before_script:
# - make docker-up-build
script:
  - make docker-up-test
after_script:
  - docker-compose down
before_install:
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv
    -in .env.enc -out .env -d
  - openssl aes-256-cbc -K $encrypted_d4c3a8cdf63e_key -iv $encrypted_d4c3a8cdf63e_iv
    -in docker.env.enc -out docker.env -d
