version: "3.7"
services:
  app:
    build:
      target: base
    image: jott-api-test
    ports:
    - 30:30
    depends_on:
    - db
    command: npm run test:unit
    tty: true

  db:
    environment:
    - MYSQL_DATABASE=$TEST_DB

