version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    restart: unless-stopped
    env_file:
    - docker.env
    ports:
    - 6030:6030
    volumes:
      - ./:/usr/app
      - /usr/app/node_modules/
    image: alberry/jott-note-service
    depends_on:
    - db
    command: npm run dev

  # redis:
  #   container_name: redis
  #   image: redis
  #   ports:
  #   - "63791:6379"
  #   volumes:
  #   - redisdata:/data
  db:
    image: mysql
    # restart: always
    # env_file:
    # - docker.env
    environment:
    - MYSQL_USER=$MYSQL_USER
    - MYSQL_PASSWORD=$MYSQL_PASSWORD
    - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
    - '33061:3306'
    expose:
    - '33061'
    volumes:
    - data-db:/var/lib/mysql


volumes:
  # redisdata:
  data-db: